### ISSUE TITLE
[Question] How to disable ligatures in Visual Studio?

### ISSUE THREAD

**Issue by ghost** [kika/fixedsys#28]
Hi, I love this font, but I don't like to use ligatures when editing code, How could it be removed in Visual studio? in Vs code there is an option, but in Visual Studio not.

Thanks!

**Comment by kika** [comment]
If the font renderer doesn't give an option to disable ligatures the only way to get rid of them is to remove them from the font. You don't even need to remove the glyphs themselves, just edit the ligatures table in the ttx file and recompile with font tools.

**Comment by ghost** [comment]
When I compile to ttf I get an error, I ended up doing it with fontforge, I don't know if it will be ideal
```
Compiling "FSEX.ttx" to "FSEX.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttx.py", line 401, in main
    process(jobs, options)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttx.py", line 374, in process
    action(input, output, options)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\misc\loggingTools.py", line 373, in wrapper
    return func(*args, **kwds)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttx.py", line 285, in ttCompile
    ttf.importXML(input)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\ttFont.py", line 335, in importXML
    reader.read()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\misc\xmlReader.py", line 48, in read
    self._parseFile(self.file)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\misc\xmlReader.py", line 73, in _parseFile
    parser.Parse(chunk, 0)
  File "C:\A\34\s\Modules\pyexpat.c", line 461, in EndElement
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\misc\xmlReader.py", line 155, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\tables\_h_e_a_d.py", line 113, in fromXML
    value = timestampFromString(value)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\fontTools\misc\timeTools.py", line 52, in timestampFromString
    assert t.weekday() == wkday_idx, '"' + value + '" has inconsistent weekday'
AssertionError: "Wed May  8 16:50:55 2016" has inconsistent weekday
(Hit any key to exit)
```

**Comment by kika** [comment]
LOL, font tools took it upon themselves to validate that May 8, 2016, is indeed Wednesday. Very important for a font compiler.

**Comment by iiiGerardoiii** [comment]
ah yes @Gexur I was also having this error, so I checked the .ttx file and line 6041 has May 8 as Wednesday:
`    <modified value="Wed May  8 16:50:55 2016"/>`

May 8 2016 was Sunday, so if you change `Wed` to `Sun` it won't throw that error anymore.
