### ISSUE TITLE
"Inconsistent weekday" assertion while converting to TTF (Python's fontTools)

### ISSUE THREAD

**Issue by RaiKoHoff** [kika/fixedsys#29]
Hello,
trying to convert the FSEX.ttx to TTF (for Windows installation), I got attached assertion!
(Python v3.8.8 64bit, fontTools 4.21.1)

Wondering, if this is a "fontTools" issue or related to FSEX.TTX definition ?

(comment-out assertion in "python38\lib\site-packages\fontTools\misc\timeTools.py", line 52", will create a installable TTF)

```
Successfully installed fonttools-4.21.1

C:\Program Files\Python38>Scripts\ttx.exe -f D:\temp\_NP3\FSEX.ttx
Compiling "D:\temp\_NP3\FSEX.ttx" to "D:\temp\_NP3\FSEX.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\fontTools\ttx.py", line 401, in main
    process(jobs, options)
  File "c:\program files\python38\lib\site-packages\fontTools\ttx.py", line 374, in process
    action(input, output, options)
  File "c:\program files\python38\lib\site-packages\fontTools\misc\loggingTools.py", line 373, in wrapper
    return func(*args, **kwds)
  File "c:\program files\python38\lib\site-packages\fontTools\ttx.py", line 285, in ttCompile
    ttf.importXML(input)
  File "c:\program files\python38\lib\site-packages\fontTools\ttLib\ttFont.py", line 335, in importXML
    reader.read()
  File "c:\program files\python38\lib\site-packages\fontTools\misc\xmlReader.py", line 48, in read
    self._parseFile(self.file)
  File "c:\program files\python38\lib\site-packages\fontTools\misc\xmlReader.py", line 73, in _parseFile
    parser.Parse(chunk, 0)
  File "C:\A\34\s\Modules\pyexpat.c", line 461, in EndElement
  File "c:\program files\python38\lib\site-packages\fontTools\misc\xmlReader.py", line 155, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "c:\program files\python38\lib\site-packages\fontTools\ttLib\tables\_h_e_a_d.py", line 113, in fromXML
    value = timestampFromString(value)
  File "c:\program files\python38\lib\site-packages\fontTools\misc\timeTools.py", line 52, in timestampFromString
    assert t.weekday() == wkday_idx, '"' + value + '" has inconsistent weekday'
AssertionError: "Wed May  8 16:50:55 2016" has inconsistent weekday
(Hit any key to exit)

```

**Comment by iiiGerardoiii** [comment]
check [this solution](https://github.com/kika/fixedsys/issues/28#issuecomment-778054203) my friend

**Comment by RaiKoHoff** [comment]
Sorry for duplication.
